#
# Long Multiplication
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2015.
#



#
#
#
include ../Makefile.inc

all: runjava runml 

runjava:
	$(JAVAC) Vehdic.java
	$(JAVARUN) Vehdic


runml:
	$(SMLRUN) <  booth.sml



# eof
