#
# Floating Point demo  - six counting - using a float for counting! Nasty.
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2015.  Alan Mycroft, Siliva Breu, Cathryn Gray.
#



#
#
#
include ../Makefile.inc

all: runC runJava

PNAME=sixthcounting

runC:
	gcc $(PNAME).c
	./a.out

runJava:
	$(JAVAC) SixthCounting.java
	$(JAVARUN) SixthCounting



# eof
