// clarvi_soc_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module clarvi_soc_mm_interconnect_0 (
		input  wire        pll_outclk0_clk,                            //                          pll_outclk0.clk
		input  wire        clarvi_0_reset_reset_bridge_in_reset_reset, // clarvi_0_reset_reset_bridge_in_reset.reset
		input  wire [13:0] clarvi_0_instr_address,                     //                       clarvi_0_instr.address
		output wire        clarvi_0_instr_waitrequest,                 //                                     .waitrequest
		input  wire        clarvi_0_instr_read,                        //                                     .read
		output wire [31:0] clarvi_0_instr_readdata,                    //                                     .readdata
		output wire        clarvi_0_instr_readdatavalid,               //                                     .readdatavalid
		output wire [13:0] onchip_memory2_0_s2_address,                //                  onchip_memory2_0_s2.address
		output wire        onchip_memory2_0_s2_write,                  //                                     .write
		input  wire [31:0] onchip_memory2_0_s2_readdata,               //                                     .readdata
		output wire [31:0] onchip_memory2_0_s2_writedata,              //                                     .writedata
		output wire [3:0]  onchip_memory2_0_s2_byteenable,             //                                     .byteenable
		output wire        onchip_memory2_0_s2_chipselect,             //                                     .chipselect
		output wire        onchip_memory2_0_s2_clken                   //                                     .clken
	);

	wire         clarvi_0_instr_translator_avalon_universal_master_0_waitrequest;   // onchip_memory2_0_s2_translator:uav_waitrequest -> clarvi_0_instr_translator:uav_waitrequest
	wire  [31:0] clarvi_0_instr_translator_avalon_universal_master_0_readdata;      // onchip_memory2_0_s2_translator:uav_readdata -> clarvi_0_instr_translator:uav_readdata
	wire         clarvi_0_instr_translator_avalon_universal_master_0_debugaccess;   // clarvi_0_instr_translator:uav_debugaccess -> onchip_memory2_0_s2_translator:uav_debugaccess
	wire  [15:0] clarvi_0_instr_translator_avalon_universal_master_0_address;       // clarvi_0_instr_translator:uav_address -> onchip_memory2_0_s2_translator:uav_address
	wire         clarvi_0_instr_translator_avalon_universal_master_0_read;          // clarvi_0_instr_translator:uav_read -> onchip_memory2_0_s2_translator:uav_read
	wire   [3:0] clarvi_0_instr_translator_avalon_universal_master_0_byteenable;    // clarvi_0_instr_translator:uav_byteenable -> onchip_memory2_0_s2_translator:uav_byteenable
	wire         clarvi_0_instr_translator_avalon_universal_master_0_readdatavalid; // onchip_memory2_0_s2_translator:uav_readdatavalid -> clarvi_0_instr_translator:uav_readdatavalid
	wire         clarvi_0_instr_translator_avalon_universal_master_0_lock;          // clarvi_0_instr_translator:uav_lock -> onchip_memory2_0_s2_translator:uav_lock
	wire         clarvi_0_instr_translator_avalon_universal_master_0_write;         // clarvi_0_instr_translator:uav_write -> onchip_memory2_0_s2_translator:uav_write
	wire  [31:0] clarvi_0_instr_translator_avalon_universal_master_0_writedata;     // clarvi_0_instr_translator:uav_writedata -> onchip_memory2_0_s2_translator:uav_writedata
	wire   [2:0] clarvi_0_instr_translator_avalon_universal_master_0_burstcount;    // clarvi_0_instr_translator:uav_burstcount -> onchip_memory2_0_s2_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (14),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (16),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) clarvi_0_instr_translator (
		.clk                    (pll_outclk0_clk),                                                   //                       clk.clk
		.reset                  (clarvi_0_reset_reset_bridge_in_reset_reset),                        //                     reset.reset
		.uav_address            (clarvi_0_instr_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (clarvi_0_instr_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (clarvi_0_instr_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (clarvi_0_instr_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (clarvi_0_instr_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (clarvi_0_instr_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (clarvi_0_instr_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (clarvi_0_instr_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (clarvi_0_instr_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (clarvi_0_instr_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (clarvi_0_instr_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (clarvi_0_instr_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (clarvi_0_instr_waitrequest),                                        //                          .waitrequest
		.av_read                (clarvi_0_instr_read),                                               //                          .read
		.av_readdata            (clarvi_0_instr_readdata),                                           //                          .readdata
		.av_readdatavalid       (clarvi_0_instr_readdatavalid),                                      //                          .readdatavalid
		.av_burstcount          (1'b1),                                                              //               (terminated)
		.av_byteenable          (4'b1111),                                                           //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                              //               (terminated)
		.av_begintransfer       (1'b0),                                                              //               (terminated)
		.av_chipselect          (1'b0),                                                              //               (terminated)
		.av_write               (1'b0),                                                              //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                              //               (terminated)
		.av_lock                (1'b0),                                                              //               (terminated)
		.av_debugaccess         (1'b0),                                                              //               (terminated)
		.uav_clken              (),                                                                  //               (terminated)
		.av_clken               (1'b1),                                                              //               (terminated)
		.uav_response           (2'b00),                                                             //               (terminated)
		.av_response            (),                                                                  //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                              //               (terminated)
		.av_writeresponsevalid  ()                                                                   //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (14),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (16),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) onchip_memory2_0_s2_translator (
		.clk                    (pll_outclk0_clk),                                                   //                      clk.clk
		.reset                  (clarvi_0_reset_reset_bridge_in_reset_reset),                        //                    reset.reset
		.uav_address            (clarvi_0_instr_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (clarvi_0_instr_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (clarvi_0_instr_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (clarvi_0_instr_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (clarvi_0_instr_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (clarvi_0_instr_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (clarvi_0_instr_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (clarvi_0_instr_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (clarvi_0_instr_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (clarvi_0_instr_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (clarvi_0_instr_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (onchip_memory2_0_s2_address),                                       //      avalon_anti_slave_0.address
		.av_write               (onchip_memory2_0_s2_write),                                         //                         .write
		.av_readdata            (onchip_memory2_0_s2_readdata),                                      //                         .readdata
		.av_writedata           (onchip_memory2_0_s2_writedata),                                     //                         .writedata
		.av_byteenable          (onchip_memory2_0_s2_byteenable),                                    //                         .byteenable
		.av_chipselect          (onchip_memory2_0_s2_chipselect),                                    //                         .chipselect
		.av_clken               (onchip_memory2_0_s2_clken),                                         //                         .clken
		.av_read                (),                                                                  //              (terminated)
		.av_begintransfer       (),                                                                  //              (terminated)
		.av_beginbursttransfer  (),                                                                  //              (terminated)
		.av_burstcount          (),                                                                  //              (terminated)
		.av_readdatavalid       (1'b0),                                                              //              (terminated)
		.av_waitrequest         (1'b0),                                                              //              (terminated)
		.av_writebyteenable     (),                                                                  //              (terminated)
		.av_lock                (),                                                                  //              (terminated)
		.uav_clken              (1'b0),                                                              //              (terminated)
		.av_debugaccess         (),                                                                  //              (terminated)
		.av_outputenable        (),                                                                  //              (terminated)
		.uav_response           (),                                                                  //              (terminated)
		.av_response            (2'b00),                                                             //              (terminated)
		.uav_writeresponsevalid (),                                                                  //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                               //              (terminated)
	);

endmodule
