lecture1_3:
	cc -Wall -c lecture1_3.c
	cc -o lecture1_3 lecture1_3.o

lecture1_4:
	cc -Wall -c lecture1_4.c
	cc -o lecture1_4 lecture1_4.o

lecture2_1:
	cc -Wall -c lecture2_1.c
	cc -o lecture2_1 lecture2_1.o

lecture2_2:
	cc -Wall -c lecture2_2.c
	cc -o lecture2_2 lecture2_2.o

lecture3:
	cc -Wall -c lecture3.c calc.c
	cc -o lecture3 lecture3.o
	cc -o calc calc.o

lecture4_2:
	cc -Wall -c lecture4_2.c
	cc -o lecture4_2 lecture4_2.o

clean:
	rm -f lecture1_3.o lecture1_3 
	rm -f lecture1_4.o lecture1_4 
	rm -f lecture2_1 lecture2_1.o
	rm -f lecture2_2 lecture2_2.o
	rm -f lecture3 lecture3.o calc calc.o
	rm -f lecture4_2 lecture4_2.o
