#
# Floating Point Output - float to ASCII characters.
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2015.  Alan Mycroft, Kathryn Gray
#



#
#
#
include ../Makefile.inc

PNAME=fpout

runC:
	gcc $(PNAME).c
	./a.out

runml:
	$(SMLRUN) <  $(PNAME).ml



# eof
