#
# Integer Output - binary to ASCII characters.
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2015.  Alan Mycroft, Silvia Breu.
#



#
#
#
include ../Makefile.inc

PNAME=bin-to-ascii


all: runC runml



runC:
	gcc $(PNAME).c
	./a.out

runml:
	$(SMLRUN) <  $(PNAME).ml



# eof
