#
# Long Division
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2015.
#



#
#
#
include ../Makefile.inc


runml:
	$(SMLRUN) <  long-division.ml
	$(SMLRUN) <  long-division-fl.ml

# eof
