#
# Adding up forwards and backwards
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2015.  Alan Mycroft, Siliva Breu, Cathryn Gray.
#



#
#
#
include ../Makefile.inc

all: runC runJava

PNAME=sumfwdback

runC:
	gcc $(PNAME).c
	./a.out

runJava:
	$(JAVAC) SumFwdBack.java
	$(JAVARUN) SumFwdBack



# eof
