#
# Investigation of NaN.
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2015.  Alan Mycroft, Silvia Breu
#



#
#
#
include ../Makefile.inc

all: runC 

PNAME=nan

runC:
	gcc $(PNAME).c -lm
	./a.out



# eof
