#
#  Non-linear component : Diode Example
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2014-15.  


#
#
#
include ../Makefile.inc

SIMUSOLVE_DIR=../lu-decomposition
CLASSPATH=  -classpath .:$(SIMUSOLVE_DIR)

# Although this is numbered two, there does not seem to be a number one, so perhaps a historical anomaly.

PNAME=DiodeExample2

run:
	javac $(CLASSPATH) $(PNAME).java
	java $(CLASSPATH) $(PNAME)



# eof
