# TCL File Generated by Component Editor 15.0
# Thu Nov 05 15:26:09 GMT 2015
# DO NOT MODIFY


# 
# PixelStream "Pixel Stream" v1.0
# Simon Moore 2015.11.05.15:26:08
# Stream pixels from memory to LCD output
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module PixelStream
# 
set_module_property DESCRIPTION "Stream pixels from memory to LCD output"
set_module_property NAME PixelStream
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Simon Moore"
set_module_property DISPLAY_NAME "Pixel Stream"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkPixelStream
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mkPixelStream.v VERILOG PATH mkPixelStream.v
add_fileset_file mkBurstRead.v VERILOG PATH mkBurstRead.v
add_fileset_file SizedFIFO.v VERILOG PATH SizedFIFO.v
add_fileset_file SyncFIFO.v VERILOG PATH SyncFIFO.v
add_fileset_file FIFO2.v VERILOG PATH FIFO2.v
add_fileset_file SyncRegister.v VERILOG PATH SyncRegister.v
add_fileset_file SyncResetA.v VERILOG PATH SyncResetA.v
add_fileset_file SyncHandshake.v VERILOG PATH SyncHandshake.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true
set_interface_property clockreset EXPORT_OF ""
set_interface_property clockreset PORT_NAME_MAP ""
set_interface_property clockreset CMSIS_SVD_VARIABLES ""
set_interface_property clockreset SVD_ADDRESS_GROUP ""

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true
set_interface_property clockreset_reset EXPORT_OF ""
set_interface_property clockreset_reset PORT_NAME_MAP ""
set_interface_property clockreset_reset CMSIS_SVD_VARIABLES ""
set_interface_property clockreset_reset SVD_ADDRESS_GROUP ""

add_interface_port clockreset_reset csi_clockreset_reset_n reset_n Input 1


# 
# connection point slave_parameters
# 
add_interface slave_parameters avalon end
set_interface_property slave_parameters addressUnits WORDS
set_interface_property slave_parameters associatedClock clockreset
set_interface_property slave_parameters associatedReset clockreset_reset
set_interface_property slave_parameters bitsPerSymbol 8
set_interface_property slave_parameters burstOnBurstBoundariesOnly false
set_interface_property slave_parameters burstcountUnits WORDS
set_interface_property slave_parameters explicitAddressSpan 0
set_interface_property slave_parameters holdTime 0
set_interface_property slave_parameters linewrapBursts false
set_interface_property slave_parameters maximumPendingReadTransactions 0
set_interface_property slave_parameters maximumPendingWriteTransactions 0
set_interface_property slave_parameters readLatency 0
set_interface_property slave_parameters readWaitTime 1
set_interface_property slave_parameters setupTime 0
set_interface_property slave_parameters timingUnits Cycles
set_interface_property slave_parameters writeWaitTime 0
set_interface_property slave_parameters ENABLED true
set_interface_property slave_parameters EXPORT_OF ""
set_interface_property slave_parameters PORT_NAME_MAP ""
set_interface_property slave_parameters CMSIS_SVD_VARIABLES ""
set_interface_property slave_parameters SVD_ADDRESS_GROUP ""

add_interface_port slave_parameters avs_s0_address address Input 4
add_interface_port slave_parameters avs_s0_writedata writedata Input 32
add_interface_port slave_parameters avs_s0_write write Input 1
add_interface_port slave_parameters avs_s0_read read Input 1
add_interface_port slave_parameters avs_s0_readdata readdata Output 32
add_interface_port slave_parameters avs_s0_waitrequest waitrequest Output 1
set_interface_assignment slave_parameters embeddedsw.configuration.isFlash 0
set_interface_assignment slave_parameters embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave_parameters embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave_parameters embeddedsw.configuration.isPrintableDevice 0


# 
# connection point master_burstreads
# 
add_interface master_burstreads avalon start
set_interface_property master_burstreads addressUnits WORDS
set_interface_property master_burstreads associatedClock clockreset
set_interface_property master_burstreads associatedReset clockreset_reset
set_interface_property master_burstreads bitsPerSymbol 8
set_interface_property master_burstreads burstOnBurstBoundariesOnly false
set_interface_property master_burstreads burstcountUnits WORDS
set_interface_property master_burstreads doStreamReads false
set_interface_property master_burstreads doStreamWrites false
set_interface_property master_burstreads holdTime 0
set_interface_property master_burstreads linewrapBursts false
set_interface_property master_burstreads maximumPendingReadTransactions 0
set_interface_property master_burstreads maximumPendingWriteTransactions 0
set_interface_property master_burstreads readLatency 0
set_interface_property master_burstreads readWaitTime 1
set_interface_property master_burstreads setupTime 0
set_interface_property master_burstreads timingUnits Cycles
set_interface_property master_burstreads writeWaitTime 0
set_interface_property master_burstreads ENABLED true
set_interface_property master_burstreads EXPORT_OF ""
set_interface_property master_burstreads PORT_NAME_MAP ""
set_interface_property master_burstreads CMSIS_SVD_VARIABLES ""
set_interface_property master_burstreads SVD_ADDRESS_GROUP ""

add_interface_port master_burstreads avm_m0_readdata readdata Input 32
add_interface_port master_burstreads avm_m0_readdatavalid readdatavalid Input 1
add_interface_port master_burstreads avm_m0_waitrequest waitrequest Input 1
add_interface_port master_burstreads avm_m0_writedata writedata Output 32
add_interface_port master_burstreads avm_m0_address address Output 31
add_interface_port master_burstreads avm_m0_read read Output 1
add_interface_port master_burstreads avm_m0_write write Output 1


# 
# connection point video
# 
add_interface video clock end
set_interface_property video clockRate 0
set_interface_property video ENABLED true
set_interface_property video EXPORT_OF ""
set_interface_property video PORT_NAME_MAP ""
set_interface_property video CMSIS_SVD_VARIABLES ""
set_interface_property video SVD_ADDRESS_GROUP ""

add_interface_port video csi_video_clk clk Input 1


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock video
set_interface_property conduit_end_0 associatedReset ""
set_interface_property conduit_end_0 ENABLED true
set_interface_property conduit_end_0 EXPORT_OF ""
set_interface_property conduit_end_0 PORT_NAME_MAP ""
set_interface_property conduit_end_0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_0 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_0 coe_hdmi_r lcd_red Output 8
add_interface_port conduit_end_0 coe_hdmi_g lcd_green Output 8
add_interface_port conduit_end_0 coe_hdmi_b lcd_blue Output 8
add_interface_port conduit_end_0 coe_hdmi_hsd lcd_hsync Output 1
add_interface_port conduit_end_0 coe_hdmi_vsd lcd_vsync Output 1
add_interface_port conduit_end_0 coe_hdmi_de lcd_de Output 1
add_interface_port conduit_end_0 csi_clockreset_clk_coe_hdmi_dclk lcd_dclk Output 1
add_interface_port conduit_end_0 CLK_GATE_coe_hdmi_dclk lcd_dclk_en Output 1

