#
# Golden Ratio Iteration
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2015.  Alan Mycroft, Siliva Breu, Cathryn Gray.
#



#
#
#
include ../Makefile.inc

all: runC runJava

PNAME=golden

runC:
	gcc $(PNAME).c -lm
	./a.out

runJava:
	$(JAVAC) Golden.java
	$(JAVARUN) Golden



# eof
