#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (* (C) 2014 DJ Greaves, University of Cambridge.                          *)

# Lower/upper decomposition
#
#
#


all:SimuSolve.class demos

demos:
	javac LUdemo.java
	java LUdemo


SimuSolve.class:SimuSolve.java
	javac SimuSolve.java

#eof
