# TCL File Generated by Component Editor 16.1
# Tue Nov 28 01:44:34 GMT 2017
# DO NOT MODIFY


# 
# TwentyFourToThreeEightBits "TwentyFourToThreeEightBits" v1.0
#  2017.11.28.01:44:34
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module TwentyFourToThreeEightBits
# 
set_module_property DESCRIPTION ""
set_module_property NAME TwentyFourToThreeEightBits
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME TwentyFourToThreeEightBits
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL TwentyFourBitsToThreeEightBits
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file TwentyFourBitsToThreeEightBits.sv SYSTEM_VERILOG PATH TwentyFourBitsToThreeEightBits.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point bits_in
# 
add_interface bits_in conduit end
set_interface_property bits_in associatedClock ""
set_interface_property bits_in associatedReset ""
set_interface_property bits_in ENABLED true
set_interface_property bits_in EXPORT_OF ""
set_interface_property bits_in PORT_NAME_MAP ""
set_interface_property bits_in CMSIS_SVD_VARIABLES ""
set_interface_property bits_in SVD_ADDRESS_GROUP ""

add_interface_port bits_in twentyFourBits export Input 24


# 
# connection point bits_out_one
# 
add_interface bits_out_one conduit end
set_interface_property bits_out_one associatedClock ""
set_interface_property bits_out_one associatedReset ""
set_interface_property bits_out_one ENABLED true
set_interface_property bits_out_one EXPORT_OF ""
set_interface_property bits_out_one PORT_NAME_MAP ""
set_interface_property bits_out_one CMSIS_SVD_VARIABLES ""
set_interface_property bits_out_one SVD_ADDRESS_GROUP ""

add_interface_port bits_out_one eightBitsOne export Output 8


# 
# connection point bits_out_two
# 
add_interface bits_out_two conduit end
set_interface_property bits_out_two associatedClock ""
set_interface_property bits_out_two associatedReset ""
set_interface_property bits_out_two ENABLED true
set_interface_property bits_out_two EXPORT_OF ""
set_interface_property bits_out_two PORT_NAME_MAP ""
set_interface_property bits_out_two CMSIS_SVD_VARIABLES ""
set_interface_property bits_out_two SVD_ADDRESS_GROUP ""

add_interface_port bits_out_two eightBitsTwo export Output 8


# 
# connection point bits_out_three
# 
add_interface bits_out_three conduit end
set_interface_property bits_out_three associatedClock ""
set_interface_property bits_out_three associatedReset ""
set_interface_property bits_out_three ENABLED true
set_interface_property bits_out_three EXPORT_OF ""
set_interface_property bits_out_three PORT_NAME_MAP ""
set_interface_property bits_out_three CMSIS_SVD_VARIABLES ""
set_interface_property bits_out_three SVD_ADDRESS_GROUP ""

add_interface_port bits_out_three eightBitsThree export Output 8

