# TCL File Generated by Component Editor 15.0
# Mon Oct 26 15:44:33 GMT 2015
# DO NOT MODIFY


# 
# EightBitsToSevenSeg "EightBitsToSevenSeg" v1.0
#  2015.10.26.15:44:33
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module EightBitsToSevenSeg
# 
set_module_property DESCRIPTION ""
set_module_property NAME EightBitsToSevenSeg
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME EightBitsToSevenSeg
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL EightBitsToSevenSeg
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file EightBitsToSevenSeg.sv SYSTEM_VERILOG PATH EightBitsToSevenSeg.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point data_in
# 
add_interface data_in conduit end
set_interface_property data_in associatedClock ""
set_interface_property data_in associatedReset ""
set_interface_property data_in ENABLED true
set_interface_property data_in EXPORT_OF ""
set_interface_property data_in PORT_NAME_MAP ""
set_interface_property data_in CMSIS_SVD_VARIABLES ""
set_interface_property data_in SVD_ADDRESS_GROUP ""

add_interface_port data_in hexval export Input 8


# 
# connection point led_pins
# 
add_interface led_pins conduit end
set_interface_property led_pins associatedClock clock
set_interface_property led_pins associatedReset reset
set_interface_property led_pins ENABLED true
set_interface_property led_pins EXPORT_OF ""
set_interface_property led_pins PORT_NAME_MAP ""
set_interface_property led_pins CMSIS_SVD_VARIABLES ""
set_interface_property led_pins SVD_ADDRESS_GROUP ""

add_interface_port led_pins digit0 led0 Output 7
add_interface_port led_pins digit1 led1 Output 7


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1

