#
# Investigation of printing significant figures.
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2015.  Alan Mycroft, Silvia Breu
#



#
#
#
include ../Makefile.inc

all: runC runJava

PNAME=printsigfig_float

runC:
	gcc $(PNAME).c
	./a.out

runJava:
	$(JAVAC) PrintSigFigFloat.java
	$(JAVARUN) PrintSigFigFloat



# eof
