#
#  Golden Ratio - gone bad.
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2015.  Alan Mycroft, Siliva Breu, Cathryn Gray.
#



#
#
#
include ../Makefile.inc

all: runC runJava

PNAME=goldenbad

runC:
	gcc $(PNAME).c
	./a.out

runJava:
	$(JAVAC) GoldenBad.java
	$(JAVARUN) GoldenBad



# eof
