#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (* (C) 2014 DJ Greaves, University of Cambridge.                          *)

# Choelesky decomposition
#
#
#


all:../lu-decomposition/SimuSolve.class
	javac CholeskyDemo.java
	java CholeskyDemo

links:
	ln -s ../lu-decomposition/SimuSolve.class

#eof
