#
#  poly 
#
# University of Cambridge Computer Laboratory - Numerical Methods Demos
# (C) DJ Greaves, 2015.  Alan Mycroft, Siliva Breu, Cathryn Gray, 
# Taken from Cleve Moler's article.
#



#
#
#
include ../Makefile.inc

all: runOctave

runOctave:
	$(OCTAVE) poly.m

PNAME=poly
