# TCL File Generated by Component Editor 16.0
# Wed Sep 14 14:51:10 BST 2016
# DO NOT MODIFY


# 
# shiftregctl "shiftregctl" v1.0
# Theo Markettos 2016.09.14.14:51:10
# Cambridge Teaching Board shift register controller
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module shiftregctl
# 
set_module_property DESCRIPTION "Cambridge Teaching Board shift register controller"
set_module_property NAME ShiftRegCtl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Theo Markettos"
set_module_property DISPLAY_NAME ShiftRegCtl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL shiftregctl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file shiftregctl.sv SYSTEM_VERILOG PATH shiftregctl.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_50m clk Input 1


# 
# connection point buttons
# 
add_interface buttons conduit end
set_interface_property buttons associatedClock ""
set_interface_property buttons associatedReset ""
set_interface_property buttons ENABLED true
set_interface_property buttons EXPORT_OF ""
set_interface_property buttons PORT_NAME_MAP ""
set_interface_property buttons CMSIS_SVD_VARIABLES ""
set_interface_property buttons SVD_ADDRESS_GROUP ""

add_interface_port buttons buttons export Output 16


# 
# connection point shiftreg_ext
# 
add_interface shiftreg_ext conduit end
set_interface_property shiftreg_ext associatedClock ""
set_interface_property shiftreg_ext associatedReset ""
set_interface_property shiftreg_ext ENABLED true
set_interface_property shiftreg_ext EXPORT_OF ""
set_interface_property shiftreg_ext PORT_NAME_MAP ""
set_interface_property shiftreg_ext CMSIS_SVD_VARIABLES ""
set_interface_property shiftreg_ext SVD_ADDRESS_GROUP ""

add_interface_port shiftreg_ext shiftreg_clk shiftreg_clk Output 1
add_interface_port shiftreg_ext shiftreg_loadn shiftreg_loadn Output 1
add_interface_port shiftreg_ext shiftreg_out shiftreg_out Input 1

